#include "tui/help.h"

const HelpEntry tui_command_help_entries[TUI_COMMAND_HELP_COUNT] = {
    { L"attach <pid>", L"attach to a running target process by its numeric PID" },
    { L"detach", L"detach from the current target; saved table entries remain inert" },
    { L"search [name]", L"filter process image names case-insensitively; omit the name to clear the filter" },
    { L"read <addr> <n>", L"read 1-128 bytes; short reads fit the status line, longer reads open the navigable Hex View" },
    { L"write <addr> <byte> [byte ...]", L"write one or more whitespace-separated hexadecimal byte pairs, for example `write 1234 90 90`" },
    { L"hex <addr>", L"open the live Hex View at a hexadecimal address" },
    { L"disasm <addr>", L"open the x64 disassembler at a hexadecimal address" },
    { L"watch <addr> <type>", L"watch one naturally aligned numeric value; pause when target CPU writes change its bytes" },
    { L"continue", L"resume the paused target and keep watching the same value" },
    { L"unwatch", L"stop watching and resume the target, keeping ordinary memory access attached" },
    { L"inject <DLL path>", L"load an x64 DLL using the Windows loader; paths may contain spaces or outer quotes. Stop watching first. Loaded DLL remains in target after detach" },
    { L"pointers <addr> [depth] [offset]", L"find main-executable pointer paths to a hex address; depth 1-3 (default 2), max nonnegative offset 0-4096 decimal (default 1024)" },
    { L"pointerfilter <addr>", L"keep paths that resolve to a new hex address after reattaching the same executable" },
    { L"structure <addr> [size]", L"inspect up to 256 bytes (default 256) at a hex address; R refreshes and marks changes" },
    { L"field <offset> <type> <label>", L"name a numeric field in the current structure; offset is hex. Setting its offset again replaces it. Layout lasts until detach or another structure is opened" },
    { L"scan <value>", L"start a fresh exact scan using the current scanner type" },
    { L"next <value>", L"re-read and retain existing results that exactly match the new value" },
    { L"type <name>", L"select i8|i16|i32|i64|u8|u16|u32|u64|f32|f64|string|aob and clear prior results" },
    { L"strenc ascii|utf16", L"select the encoding used by string scans" },
    { L"addentry <addr> <type> <label>", L"save a fixed-width address under an ASCII label" },
    { L"delentry <index>", L"remove an address-table entry by its zero-based index" },
    { L"entrylabel <index> <label>", L"replace an entry's ASCII label" },
    { L"lockentry <index> <value>", L"write a fixed value to an entry every 50 ms while its target remains attached" },
    { L"unlockentry <index>", L"stop writing the locked value for an entry" },
    { L"saveentry <filename>", L"save the current address table to a strict text file" },
    { L"loadentry <filename>", L"transactionally load an address table; persisted locks remain disabled" },
    { L"help / ? / quit / exit", L"open panel help or close MemForge" },
};
